name: Build and Push Docker Images

on:
  push:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # TEMP debug step — remove after first successful run
      - name: Debug: check DOCKERHUB_USER presence
        run: |
          if [ -z "${DOCKERHUB_USER}" ]; then
            echo "DOCKERHUB_USER is EMPTY"
            exit 1
          else
            echo "DOCKERHUB_USER is set"
          fi

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USER }}
          password: ${{ env.DOCKERHUB_TOKEN }}

      - name: Build and push frontend image
        uses: docker/build-push-action@v6
        with:
          # frontend is repo root (since no ./frontend folder exists)
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.DOCKERHUB_USER }}/frontend-app:latest
            ${{ env.DOCKERHUB_USER }}/frontend-app:${{ github.sha }}
